server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/postsbase
    username: root
    password: testTEST
  liquibase:
    change-log: db/chngelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
  mvc:
    hiddenmethod:
      filter:
        enabled: true
blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005

