server:
  port: ${PORT:8080}
spring:
  datasource:
    url: jdbc:${JAWSDB_URL:mysql://localhost:3306/postsbase}
    username: root
    password: testTEST
#  liquibase:
#    change-log: db/chngelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: nik80568@gmail.com
    password: nik80568
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: false
cloudinary:
  cloud_name: hnlgwe8wh
  api_key: 649347388144627
  api_secret: ziCvB7zKhhzlqTr-buAmBk3_8NI

blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005

